language: minimal
sudo: required
services:
  - docker
script: make
env:
  global:
  - secure: iudV//s4G0V9UOcD/kmtDqUS8MZVotidj6EtqTCahX+tBi6hPD7IxsgTFgBm0nNoL7Q5LO0G1VspKukn0r1u80w5WsOq1RvJTPj6fJvV6mvWv6OKRStVvEVLoYEXf9xOOtsN7V14EW2cgsCaHgHDxCB3ct83wmUDKUeWtZYKGuQLk7JJCH+GrfWr18rXEj+lrxs4gg45yAE7rMnmWSLfxyNrjaaehtRhV5OxVBegRbUVgpn7FeIJqqoHtAw/+u0j4Z00UCRiuMs20EZzh8npsb8VMrauUHFBTywUkZK0u55B1uT0Z4Apl83vb4g++O4jaH9bkqqM4LIOSQgwkH2pUMbUGb5J4ZxEnwBo0y9iyvZ3p5PkGWRkDuPo/0nW8q680Vfc3kfW7HSngghXCXvVVc6WaszKCAWj+Fh2ui3B0yxXd8Z6W6/wsDfKTVOf0IrfJRRiXeMsRNVb0r+rMfe13DGE0U3dpHNeOM5s3rjcnKDpZHtF+cxqwcFtXI1/ElUZ1KdDn0KJWD1C+oXGJEYg0qCBsQ5bObImRGyKX72Jm+iqmgR/k+6SiNd6iC2HcY6WJF0gngSJzEFULZnA6W6dvDcVIPxhtGBifr7WRsLDWjNxwr1pcrJDLSj5vK7AxrLUctMk4hW9Cc1to4Od1UlKIhdKbhEWg9rpWacxjL59UY0=
  - secure: EghnCWHR9SR3tQu6lN0SEFoA5xj6RkBnQhtFexK76Q592AKa2N4tDBpnpmRwwHIxyl8RoQAFTEcySHeUEn3Q3V348288dWkhNKzKzDEc+G3PcIPg340kYfedTBy6XEGOaRgBFYpFoVWdP1vsem9fw/hoTZm1jiil/o9oKgrW7CHKup0i++A9mOuwI2bC5fJBKatyzBYN8RiJ9Ldg/YVnp07EaySGq7PwxqdfTIKzQ29QysNnNRF0/ObJsijfY8NFZ7foAOEURiPqU29fucsISXfmGYg1P5AQKWbIc9r/sO2xZyE32VasM/3x6ZB3mlCCZsKcG3+9PRkhlyuV1TJhxG4wP1Cjd7z8Cg6ToWFXTaoI7Gb8TsjtmDlmTZwWCIHLtn3jOu/y+c7xGJj9GjLptiR1JESaKad1MA7X6NmoW+WzsgaNlrev+stz9pX5PUwbhIF8TjiHAAvakP9eD+JMhykN7QBkgN/+cajGNFDbpZ+hkHY9ivSuiIN2CwzJSjHfCeUvt1alhuRo1+0sh1guTrt6lLJNPK/hT2X2yLh5lITDjhTLLiVeC/mZ5IN/RQMT6Jm08VGVRRFtrotbc2FJ+uCtTWuOPPdIqp85Tv14BhietHOA7/yK+068Yl8A1N0GmrlX14flj1ir8J1q+0DyXCf3P1zGXS21iHjbBLjJwd8=
deploy:
  - provider: script
    script: make publish
    on:
      branch: master
      tags: true