version: "3.6"
services:
  etcd0:
    image: kontena/etcd:2.3.7
    command: --name etcd0 --data-dir /var/lib/etcd --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://etcd0:2379 --initial-cluster etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380 --listen-peer-urls http://0.0.0.0:2380 --initial-advertise-peer-urls http://etcd0:2380

  etcd1:
    image: quay.io/coreos/etcd:v3.0
    entrypoint: [ "/usr/local/bin/etcd" ]
    command: --name etcd1 --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://etcd1:2379 --initial-cluster etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380 --listen-peer-urls http://0.0.0.0:2380  --initial-advertise-peer-urls http://etcd1:2380

  # etcd2:
  #   image: quay.io/coreos/etcd:v3.1
  #   entrypoint: [ "/usr/local/bin/etcd" ]
  #   command: --name etcd2 --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://etcd2:2379 --initial-cluster etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380 --listen-peer-urls http://0.0.0.0:2380  --initial-advertise-peer-urls http://etcd2:2380

  tools:
    image: etcdtesthelper
    build:
      context: ./
      dockerfile: "Dockerfile.testhelper"
    environment:
     - "ETCDCTL_ENDPOINTS=http://etcd0:2379"
    command: -c "sleep 1d" # Keeps container running
    links:
      - etcd0