version: "3.6"
services:
  etcd:
    build: .
    image: krates/etcd:2.3.7
    command: --listen-client-urls http://0.0.0.0:2379 --advertise-client-urls http://etcd:2379

  tools:
    image: krates/toolbox:2.7.0-2
    environment:
      - "ETCDCTL_ENDPOINTS=http://etcd:2379"
    volumes:
        - "./test:/test:ro"
    links:
      - etcd